# Generated by Django 5.0.7 on 2025-03-16 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_feedback_options_alter_feedback_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodtracker',
            options={},
        ),
        migrations.RemoveField(
            model_name='periodtracker',
            name='created_at',
        ),
        migrations.AddField(
            model_name='periodtracker',
            name='days_until_next',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='periodtracker',
            name='cycle_length',
            field=models.IntegerField(),
        ),
    ]
